/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import bd.DAO;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Motivo;
import model.Rut;
import model.Usuario;

/**
 *
 * @author N1CK PL4Y
 */
public class Solicitudes extends javax.swing.JFrame {
    String rutIng;
    DAO oDao;
    /**
     * Creates new form Solicitudes
     */
    public Solicitudes(String rutTrabajador) {
        rutIng = rutTrabajador;
        initComponents();
        cargarCbo();
        
        setTitle("Solicitudes");
    }

    private Solicitudes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rutU = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombreU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cuentaU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellido1U = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apellido2U = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        estadoU = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboMotivo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnEnviar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Rut Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        rutU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rutUKeyReleased(evt);
            }
        });
        jPanel1.add(rutU, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 150, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel1.add(nombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, -1));

        jLabel3.setText("N° Cuenta:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));
        jPanel1.add(cuentaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 140, -1));

        jLabel4.setText("Apellido Paterno:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        jPanel1.add(apellido1U, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, -1));

        jLabel5.setText("Apellido Materno:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));
        jPanel1.add(apellido2U, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 120, -1));

        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(estadoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 100, -1));

        jLabel6.setText("Motivo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jPanel1.add(cboMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, -1));

        jLabel8.setText("Detalle Solicitud:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 330, 130));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        LoginTrabajador login = new LoginTrabajador();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        getUsuario(rutU.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        int n = 0;
        try {
            // TODO add your handling code here:
            oDao = new DAO();
            switch (cboMotivo.getSelectedIndex()) {
                case 0:
                    JOptionPane.showMessageDialog(rootPane, "Debe selecionar una opcion");
                    break;
                case 1:
                    n = cboMotivo.getSelectedIndex();
                    oDao.estadoCuenta(Integer.parseInt(cuentaU.getText()), 1);
                    oDao.solicitud(Integer.parseInt(cuentaU.getText()), rutIng, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                case 2:
                    n = cboMotivo.getSelectedIndex();
                    oDao.estadoCuenta(Integer.parseInt(cuentaU.getText()), 0);
                    oDao.solicitud(Integer.parseInt(cuentaU.getText()), rutIng, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                case 3:
                    n = cboMotivo.getSelectedIndex();
                    oDao.solicitud(Integer.parseInt(cuentaU.getText()), rutIng, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                case 4:
                    n = cboMotivo.getSelectedIndex();
                    oDao.solicitud(Integer.parseInt(cuentaU.getText()), rutIng, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                case 5:
                    n = cboMotivo.getSelectedIndex();
                    oDao.solicitud(Integer.parseInt(cuentaU.getText()), rutIng, txtDescripcion.getText(), n);
                    JOptionPane.showMessageDialog(rootPane, "Enviada");
                    break;
                default:
                    break;
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void rutUKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rutUKeyReleased
        Rut oRut = new Rut();
        rutU.setText(oRut.formatear(rutU.getText()));
    }//GEN-LAST:event_rutUKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Solicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Solicitudes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido1U;
    private javax.swing.JTextField apellido2U;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboMotivo;
    private javax.swing.JTextField cuentaU;
    private javax.swing.JTextField estadoU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreU;
    private javax.swing.JTextField rutU;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables
    private void cargarCbo() {
        cboMotivo.removeAllItems();
        cboMotivo.addItem("Seleccione un motivo");
        try {
            oDao = new DAO();
            List<Motivo> motivo = oDao.getMotivo();
            for (Motivo motivo1 : motivo) {
                cboMotivo.addItem(motivo1.getDetalle());
            }
//            if (oMotivo!=null) {
//                cboMotivo.addItem(oMotivo.getDetalle());
//            }

        } catch (SQLException ex) {
            Logger.getLogger(Solicitudes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getUsuario(String r_Usuario) {

        try {
            oDao = new DAO();
            Usuario oUsuario;
            oUsuario = oDao.getUserRegisted(r_Usuario);
            if (oUsuario != null) {
               nombreU.setText(oUsuario.getNombre());
               cuentaU.setText(""+oUsuario.getN_Cuenta());
               apellido1U.setText(oUsuario.getApellido_P());
               apellido2U.setText(oUsuario.getApellido_M());
               if (oUsuario.isEstado()) {
                    estadoU.setText("Activa");
                } else {
                    estadoU.setText("Desactiva");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(M_principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
