/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import bd.DAO;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Tipo_cuenta;
import model.Usuario;

/**
 *
 * @author N1CK PL4Y
 */
public class Transferencia extends javax.swing.JFrame {

    int cuenta_ori;
    DAO oDao;
    DAO oDao2;

    /**
     * Creates new form Transferencia
     */
    public Transferencia(int cuenta) {
        cuenta_ori = cuenta;
        txtDesde.setText("" + cuenta_ori);
        initComponents();
        cargarCbo();
        cargarCbo_des();
    }

    private Transferencia() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboOri = new javax.swing.JComboBox<>();
        txtRutH = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCuentaH = new javax.swing.JTextField();
        cboDes = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNombreH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMontoH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMensajeH = new javax.swing.JTextField();
        btnTransferir = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Desde:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        txtDesde.setEditable(false);
        jPanel1.add(txtDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 11, 141, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Hacia:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 56, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Rut:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        jPanel1.add(cboOri, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 11, 124, -1));
        jPanel1.add(txtRutH, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 83, 141, -1));

        jButton1.setText("Buscar Destinatario");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 82, -1, -1));

        jLabel4.setText("N° Cuenta:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, -1, -1));
        jPanel1.add(txtCuentaH, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 123, 140, -1));

        jPanel1.add(cboDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 123, 125, -1));

        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 164, -1, -1));
        jPanel1.add(txtNombreH, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 161, 142, -1));

        jLabel6.setText("Monto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel1.add(txtMontoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 140, -1));

        jLabel8.setText("Mensaje:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtMensajeH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajeHActionPerformed(evt);
            }
        });
        jPanel1.add(txtMensajeH, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 270, -1));

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        M_principal principal = new M_principal(getRutUsuario(cuenta_ori));
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        TransferirMonto(cuenta_ori, Integer.parseInt(txtCuentaH.getText()), Integer.parseInt(txtMontoH.getText()), txtMensajeH.getText(), cboOri.getSelectedIndex(), cboDes.getSelectedIndex());
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void txtMensajeHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensajeHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cboDes;
    private javax.swing.JComboBox<String> cboOri;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCuentaH;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtMensajeH;
    private javax.swing.JTextField txtMontoH;
    private javax.swing.JTextField txtNombreH;
    private javax.swing.JTextField txtRutH;
    // End of variables declaration//GEN-END:variables
private String getRutUsuario(int n_cuenta) {
        try {
            oDao = new DAO();
            String rutV;
            rutV = oDao.getRutUsuario(n_cuenta);
            return rutV;
        } catch (SQLException ex) {
            Logger.getLogger(Transferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    private void TransferirMonto(int _Origen, int _Destino, int _Monto, String mensaje, int i, int id_D) {
        try {
            oDao = new DAO();
            //oDao2=new DAO();
            Usuario oUsuario = new Usuario();
            oUsuario = oDao.getUserRegisted(getRutUsuario(cuenta_ori));
            //oUsuario.getSaldo();
            M_principal oM_principal;
            if (cboOri.getSelectedIndex() == 3) {
                //alerta cuenta de ahorro
                JOptionPane.showMessageDialog(rootPane, "Imposible de realizar");
            } else {
                if (_Monto > 0 && _Monto < 200000) {
                    oDao.transferencia(_Origen, _Destino, _Monto, i, mensaje, id_D);
                    JOptionPane.showMessageDialog(rootPane, "Transferencia Exitosa");
                    oM_principal = new M_principal(getRutUsuario(cuenta_ori));
                    oM_principal.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Monto invalido");
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Transferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void getUsuario(String r_Usuario) {

        try {
            oDao = new DAO();
            Usuario oUsuario;
            oUsuario = oDao.getUserRegisted(r_Usuario);
            if (oUsuario != null) {

            }
        } catch (SQLException ex) {
            Logger.getLogger(M_principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarCbo() {
        cboOri.removeAllItems();
        try {
            //cboOri.addItem("Seleccione una opcion");
            oDao = new DAO();
            List<Tipo_cuenta> t_cuenta = oDao.getT_cuenta();
            for(Tipo_cuenta oTipo_cuenta:t_cuenta){
                cboOri.addItem(oTipo_cuenta.getDetalle());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Transferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void cargarCbo_des() {
        cboDes.removeAllItems();
        try {
            //cboOri.addItem("Seleccione una opcion");
            oDao = new DAO();
            List<Tipo_cuenta> t_cuenta = oDao.getT_cuenta();
            for(Tipo_cuenta oTipo_cuenta:t_cuenta){
                cboDes.addItem(oTipo_cuenta.getDetalle());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Transferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }

}
